workflow/rules/fastp_pe.smk

feat: make it possible to use profiles

Resources settings

---

workflow/rules/merged.smk

feat: add resources to merged

---

workflow/rules/fastp_pe.smk

fix: handle case when rule have settings but no resources se

fix: handle case when rule have settings but no resources set

---

.github/workflows/snakemake-dry-run.yaml

fix: dry run for fastp + merge workflow.

fix: dry run for fastp + merge workflow.

---

release-please.yam
release-please.yaml

feat: added release-please workflow

---

config/config.yaml

chore: change to latest container

---

requirements.txt
workflow/rules/common.smk
workflow/rules/fastp.smk

fix: added barcode to fastq names to handle merging

---

.github/workflows/integration.yaml

ci: use same version for conda and singularity test

---

.tests/integration/config.yaml
workflow/schemas/units.schema.yaml

fix: update to lasted tools image

---

workflow/rules/common.smk
workflow/rules/merged.smk

fix: add missing temp for output merged

---

.github/workflows/integration.yaml
.github/workflows/snakemake-dry-run.yaml

ci: update dependencies

---

workflow/rules/sortmerna.smk

fix: flag output directories correctly

---

.tests/jenkins/Jenkinsfile

fix: copy config.yaml to correct location for jenkins

---

requirements.txt

fix: update hydra-genetics version

---

requirements.txt
workflow/rules/common.smk

feat: update snakemake version

---

.github/workflows/integration.yaml

fix: set strict mode fore conda

---

workflow/rules/common.smk
workflow/schemas/units.schema.yaml

fix: allow - in barcode string

---

.tests/jenkins/Jenkinsfile

refactor: remove duplicate argument

---

workflow/rules/common.smk

feat(common): update flowcell constraint

---

workflow/rules/fastp.smk

chore: add fastp-ending to fastp logs for multiqc

---

workflow/rules/common.smk
workflow/rules/fastp.smk

fix: Wildcard order fix

---

README.md

previous commit change output name of fastqfiles for fastp and this update will introduce compatibility errors with modules that depends on prealignment and use the output from fastp

fix!: update readme and introduce breaking change message

---

.github/workflows/integration.yaml
workflow/envs/fastp.yaml
workflow/envs/merged.yaml
workflow/envs/sortmerna.yaml
workflow/rules/fastp.smk
workflow/rules/merged.smk
workflow/rules/sortmerna.smk

we will drop support for conda, since it constantly breaking even though code hasn't been updated.

ci: remove conda testing

---

.github/CODEOWNERS

feat: remove marrip and support for conda

---

docs/requirements.txt
docs/softwares.md
mkdocs.yml

feat: apply plugin used to convert schemas to tables

---

docs/requirements.txt
docs/softwares.md
mkdocs.yml
workflow/schemas/rules.schema.yaml

feat: add rule parameter table via plugin

---

README.md
mkdocs.yml

docs: update readme with link to readthe docs

---

docs/requirements.txt

mkdocs-yaml-schema-plugin from 0.2.2 to 0.2.3
mkdocs-snakemake-rule-plugin from 0.3.0 to 0.3.2
in `docs/requirements.txt`

chore: update mkdocs-yaml-schema-plugin and mkdocs-snakemake-rule-plugin

---

docs/requirements.txt

docs: fix rtd rule plugin bug

---

.github/workflows/test-build-mkdocs.yaml

ci: test build mkdocs

---

workflow/rules/pbmarkdup.smk

fix(pbmarkdup): redirect long info correctly

---

workflow/rules/pbmarkdup.smk

fix(pbmarkdup): add missing params.extra to shell

---

.tests/integration/config.yaml
config/config.yaml
docs/softwares.md
workflow/Snakefile
workflow/rules/common.smk
workflow/rules/seqtk.smk
workflow/schemas/config.schema.yaml
workflow/schemas/resources.schema.yaml
workflow/schemas/rules.schema.yaml

feat: added seqtk_subsample rule

---

docs/images/all.dot
docs/intro.md

docs: updated dag grapgh

---

.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/release-please.yaml
.github/workflows/snakemake-dry-run.yaml
.github/workflows/test-build-mkdocs.yaml

chore: update release-please

---

.github/workflows/release-please.yaml

feat: new release-please

---

.github/workflows/release-please.yaml

fix: release-please to master instead of develop
